; PlatformIO Project Configuration File for Arduino UNO
; IC Logic Gate Tester (74HC00, 74HC02, 74HC04, 74HC08, 74HC32)

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
monitor_echo = yes
build_flags = 
    -D BAUD_RATE=115200
